export interface Tool {
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  category: string;
  icon: string;
  keywords: string[];
}

export interface Category {
  id: string;
  name: string;
  description: string;
  icon: string;
}

export const categories: Category[] = [
  {
    id: "dev",
    name: "Developer Tools",
    description: "Format, encode, decode, and hash code and data structures.",
    icon: "Code",
  },
  {
    id: "design",
    name: "Design & Graphics",
    description: "Create gradients, color palettes, and generate QR codes.",
    icon: "Palette",
  },
  {
    id: "text",
    name: "Text & Content",
    description: "Analyze, format, convert, and preview textual content.",
    icon: "FileText",
  },
  {
    id: "utility",
    name: "Utility Tools",
    description: "Generate passwords, test regular expressions, and convert units.",
    icon: "Wrench",
  },
];

export const tools: Tool[] = [
  {
    slug: "json-formatter",
    name: "JSON Formatter & Validator",
    description: "Beautify, minify, validate, and debug JSON data with syntax highlighting.",
    longDescription: "Use our free online JSON Formatter and Validator to clean, format, validate, and parse raw JSON strings. It highlights errors in real time, generates clean trees, and lets you minify JSON with a single click. Essential for API testing and web debugging.",
    category: "dev",
    icon: "Braces",
    keywords: ["json formatter", "json validator", "beautify json", "minify json", "json parser", "format json online"],
  },
  {
    slug: "password-generator",
    name: "Secure Password Generator",
    description: "Create highly secure, customizable passwords to protect your accounts.",
    longDescription: "Generate strong and random passwords with our Secure Password Generator. Customize the length, include uppercase, lowercase, numbers, and symbols. Perfect for creating unhackable credentials for your accounts.",
    category: "utility",
    icon: "Key",
    keywords: ["password generator", "secure password", "random password", "password strength", "strong password generator"],
  },
  {
    slug: "diff-checker",
    name: "Text Diff Checker",
    description: "Compare two text snippets side-by-side or inline to find code or text differences.",
    longDescription: "Compare two text versions side-by-side to highlight differences. Use it to check code diffs, text drafts, and formatting updates. Simple, secure, and fully client-side.",
    category: "dev",
    icon: "FileDiff",
    keywords: ["diff checker", "text comparison", "compare code", "side-by-side diff", "text merge comparator"],
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate customizable QR codes for URLs, text, or contacts with instant download.",
    longDescription: "Create custom QR codes for your websites, social media links, or contact info. Choose custom sizes, colors, and download them instantly in SVG format. Fully customizable and free.",
    category: "design",
    icon: "QrCode",
    keywords: ["qr code generator", "make qr code", "free qr code creator", "custom qr code", "qr code maker"],
  },
  {
    slug: "case-converter",
    name: "Text Case Converter",
    description: "Convert text cases between UPPERCASE, lowercase, Title Case, camelCase, and more.",
    longDescription: "Convert case formatting of any text online. Supports UPPERCASE, lowercase, Title Case, camelCase, snake_case, PascalCase, and slugification. Also includes a real-time character and word counter.",
    category: "text",
    icon: "CaseSensitive",
    keywords: ["case converter", "text case", "uppercase to lowercase", "title case generator", "slugify text", "camelcase converter"],
  },
  {
    slug: "base64-codec",
    name: "Base64 Encoder / Decoder",
    description: "Encode and decode plain text or files to and from Base64 format securely.",
    longDescription: "Safely encode and decode strings and files to and from Base64. A critical developer utility for data transmission, API payloads, and image URI generation. 100% client-side data safety.",
    category: "dev",
    icon: "Binary",
    keywords: ["base64 encoder", "base64 decoder", "base64 format", "base64 string", "encode base64", "decode base64"],
  },
  {
    slug: "markdown-previewer",
    name: "Live Markdown Editor & Previewer",
    description: "Write and edit Markdown syntax with a real-time visual HTML rendering side-by-side.",
    longDescription: "A real-time Markdown editor and renderer. Write markdown syntax, visualize the formatted HTML live, and copy the compiled HTML with one click. Ideal for blog writing and documentation formatting.",
    category: "text",
    icon: "Eye",
    keywords: ["markdown editor", "markdown previewer", "live markdown converter", "markdown to html", "write markdown online"],
  },
  {
    slug: "url-codec",
    name: "URL Encoder / Decoder",
    description: "Percent-encode or decode URL query strings and path parameters safely.",
    longDescription: "Easily encode or decode URL components using percent-encoding. Standardize URL query strings to avoid broken page paths or extract readable parameters from encoded links.",
    category: "dev",
    icon: "Link2",
    keywords: ["url encoder", "url decoder", "url percent encoding", "decode url string", "safe url query format"],
  },
  {
    slug: "hash-generator",
    name: "Cryptographic Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, and SHA-512 hashes instantly from any text input.",
    longDescription: "Securely generate cryptographic checksums and hashes online. Computes MD5, SHA-1, SHA-256, and SHA-512 hashes from input strings instantly inside your browser. Perfect for file verification and password hashing tests.",
    category: "dev",
    icon: "Lock",
    keywords: ["hash generator", "sha256 generator", "md5 generator", "sha1 generator", "cryptographic hash", "online hash maker"],
  },
  {
    slug: "color-palette",
    name: "Color Palette Generator",
    description: "Generate stunning color palettes, lock colors, copy HEX/RGB codes, and export configurations.",
    longDescription: "Generate cohesive and vibrant color palettes for websites and designs. Lock colors you love, pick custom shades, and copy HEX or RGB codes instantly. Perfect for designers and developers starting new projects.",
    category: "design",
    icon: "Palette",
    keywords: ["color palette generator", "color scheme", "hex color codes", "color palette generator web", "design color picker"],
  },
  {
    slug: "css-gradient",
    name: "CSS Gradient Generator",
    description: "Create linear and radial gradients visually, adjust angles and color stops, and export CSS.",
    longDescription: "Create rich, multi-color CSS gradients visually. Adjust gradient types (linear or radial), modify angles, customize color stops, and export the copy-pasteable CSS code instantly.",
    category: "design",
    icon: "Sparkles",
    keywords: ["css gradient generator", "linear gradient", "radial gradient", "gradient css maker", "visual gradient creator"],
  },
  {
    slug: "regex-tester",
    name: "Interactive Regex Tester",
    description: "Test regular expressions in real-time with match highlighting and group breakdowns.",
    longDescription: "Write and test regular expressions in real time. Highlights matches in your target text, displays capture group breakdowns, and verifies regex syntax with interactive color indicators.",
    category: "utility",
    icon: "SearchCode",
    keywords: ["regex tester", "regular expression checker", "regex helper", "test regex online", "regex match highlighter"],
  },

  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and verify JWT tokens instantly.",
    longDescription: "Securely decode JSON Web Tokens without sending them to a server.",
    category: "dev",
    icon: "Terminal",
    keywords: ["jwt decoder", "dev", "jwt decoder"],
  },
  {
    slug: "html-entity-encoder",
    name: "HTML Entity Encoder",
    description: "Encode or decode HTML entities.",
    longDescription: "Convert special characters to their corresponding HTML entities.",
    category: "dev",
    icon: "Code",
    keywords: ["html entity encoder", "dev", "html entity encoder"],
  },
  {
    slug: "url-parser",
    name: "URL Parser",
    description: "Parse URLs into their components.",
    longDescription: "Extract protocol, host, port, path, and query parameters from any URL.",
    category: "dev",
    icon: "Link2",
    keywords: ["url parser", "dev", "url parser"],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUIDs (v4).",
    longDescription: "Create unique identifiers instantly for your database records.",
    category: "utility",
    icon: "Wrench",
    keywords: ["uuid generator", "utility", "uuid generator"],
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate dummy text for designs.",
    longDescription: "Generate customizable paragraphs of lorem ipsum text.",
    category: "text",
    icon: "FileText",
    keywords: ["lorem ipsum generator", "text", "lorem ipsum"],
  },
  {
    slug: "color-contrast",
    name: "Color Contrast Checker",
    description: "Check WCAG color contrast.",
    longDescription: "Ensure your text colors pass accessibility guidelines against backgrounds.",
    category: "design",
    icon: "Eye",
    keywords: ["color contrast checker", "design", "color contrast"],
  },
  {
    slug: "bcrypt-generator",
    name: "Bcrypt Hash Generator",
    description: "Hash passwords using bcrypt.",
    longDescription: "Generate secure bcrypt hashes with configurable salt rounds.",
    category: "dev",
    icon: "Lock",
    keywords: ["bcrypt hash generator", "dev", "bcrypt generator"],
  },
  {
    slug: "json-to-csv",
    name: "JSON to CSV",
    description: "Convert JSON data to CSV.",
    longDescription: "Instantly transform JSON arrays into spreadsheet-ready CSV files.",
    category: "dev",
    icon: "Braces",
    keywords: ["json to csv", "dev", "json to csv"],
  },
  {
    slug: "csv-to-json",
    name: "CSV to JSON",
    description: "Convert CSV data to JSON.",
    longDescription: "Turn comma-separated values into a JSON array.",
    category: "dev",
    icon: "Braces",
    keywords: ["csv to json", "dev", "csv to json"],
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Beautify SQL queries.",
    longDescription: "Format messy SQL queries into readable, indented code.",
    category: "dev",
    icon: "SearchCode",
    keywords: ["sql formatter", "dev", "sql formatter"],
  },
  {
    slug: "css-minifier",
    name: "CSS Minifier",
    description: "Compress CSS code.",
    longDescription: "Remove whitespace and comments to reduce CSS file size.",
    category: "dev",
    icon: "Code",
    keywords: ["css minifier", "dev", "css minifier"],
  },
  {
    slug: "js-minifier",
    name: "JS Minifier",
    description: "Compress JavaScript code.",
    longDescription: "Minify JS code to optimize payload delivery.",
    category: "dev",
    icon: "Terminal",
    keywords: ["js minifier", "dev", "js minifier"],
  },
  {
    slug: "html-minifier",
    name: "HTML Minifier",
    description: "Compress HTML markup.",
    longDescription: "Remove unnecessary whitespace from HTML files.",
    category: "dev",
    icon: "Code",
    keywords: ["html minifier", "dev", "html minifier"],
  },
  {
    slug: "base32-codec",
    name: "Base32 Encoder/Decoder",
    description: "Encode strings to Base32.",
    longDescription: "Convert text or data into Base32 format and back.",
    category: "dev",
    icon: "Binary",
    keywords: ["base32 encoder/decoder", "dev", "base32 codec"],
  },
  {
    slug: "hex-to-rgb",
    name: "Hex to RGB",
    description: "Convert Hex colors to RGB.",
    longDescription: "Quickly translate web colors into RGB values.",
    category: "design",
    icon: "Palette",
    keywords: ["hex to rgb", "design", "hex to rgb"],
  },
  {
    slug: "rgb-to-hex",
    name: "RGB to Hex",
    description: "Convert RGB colors to Hex.",
    longDescription: "Translate RGB values into web-ready hex codes.",
    category: "design",
    icon: "Palette",
    keywords: ["rgb to hex", "design", "rgb to hex"],
  },
  {
    slug: "text-reverser",
    name: "Text Reverser",
    description: "Reverse any string of text.",
    longDescription: "Flip text backwards instantly.",
    category: "text",
    icon: "FileText",
    keywords: ["text reverser", "text", "text reverser"],
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words and characters.",
    longDescription: "Get detailed statistics on word count, reading time, and character limits.",
    category: "text",
    icon: "FileText",
    keywords: ["word counter", "text", "word counter"],
  },
  {
    slug: "markdown-to-html",
    name: "Markdown to HTML",
    description: "Convert Markdown to HTML.",
    longDescription: "Compile markdown syntax into standard HTML tags.",
    category: "dev",
    icon: "Code",
    keywords: ["markdown to html", "dev", "markdown to html"],
  },
  {
    slug: "html-to-markdown",
    name: "HTML to Markdown",
    description: "Convert HTML to Markdown.",
    longDescription: "Extract text and formatting from HTML into markdown format.",
    category: "dev",
    icon: "Code",
    keywords: ["html to markdown", "dev", "html to markdown"],
  },
  {
    slug: "unix-timestamp",
    name: "Unix Timestamp Converter",
    description: "Convert epoch timestamps.",
    longDescription: "Translate Unix epoch time into human-readable dates.",
    category: "dev",
    icon: "Terminal",
    keywords: ["unix timestamp converter", "dev", "unix timestamp"],
  },
  {
    slug: "chmod-calculator",
    name: "Chmod Calculator",
    description: "Calculate Linux file permissions.",
    longDescription: "Generate numeric or symbolic chmod permissions.",
    category: "dev",
    icon: "Lock",
    keywords: ["chmod calculator", "dev", "chmod calculator"],
  },
  {
    slug: "crontab-generator",
    name: "Crontab Generator",
    description: "Generate cron schedule expressions.",
    longDescription: "Build and understand cron job scheduling syntax easily.",
    category: "dev",
    icon: "Terminal",
    keywords: ["crontab generator", "dev", "crontab generator"],
  },
  {
    slug: "regex-matcher",
    name: "Regex Matcher",
    description: "Test regex against sample text.",
    longDescription: "Find all matches of a regular expression in a given string.",
    category: "dev",
    icon: "SearchCode",
    keywords: ["regex matcher", "dev", "regex matcher"],
  },
  {
    slug: "xml-formatter",
    name: "XML Formatter",
    description: "Beautify XML documents.",
    longDescription: "Add proper indentation to raw XML strings.",
    category: "dev",
    icon: "Code",
    keywords: ["xml formatter", "dev", "xml formatter"],
  },
  {
    slug: "json-validator",
    name: "JSON Validator",
    description: "Validate JSON syntax.",
    longDescription: "Check if your JSON string is properly formatted and find errors.",
    category: "dev",
    icon: "Check",
    keywords: ["json validator", "dev", "json validator"],
  },
  {
    slug: "svg-optimizer",
    name: "SVG Optimizer",
    description: "Compress SVG images.",
    longDescription: "Remove unnecessary cruft from SVG files to reduce size.",
    category: "design",
    icon: "Sparkles",
    keywords: ["svg optimizer", "design", "svg optimizer"],
  },
  {
    slug: "password-checker",
    name: "Password Strength Checker",
    description: "Analyze password complexity.",
    longDescription: "Check how long it would take to crack a password.",
    category: "utility",
    icon: "Shield",
    keywords: ["password strength checker", "utility", "password checker"],
  },
  {
    slug: "random-string",
    name: "Random String Generator",
    description: "Generate random text strings.",
    longDescription: "Create random alphanumeric strings of any length.",
    category: "utility",
    icon: "Sparkles",
    keywords: ["random string generator", "utility", "random string"],
  },
  {
    slug: "text-diff",
    name: "Text Diff Checker",
    description: "Compare two texts for differences.",
    longDescription: "Highlight additions and deletions between two strings.",
    category: "text",
    icon: "FileDiff",
    keywords: ["text diff checker", "text", "text diff"],
  },
  {
    slug: "yaml-to-json",
    name: "YAML to JSON",
    description: "Convert YAML to JSON.",
    longDescription: "Translate YAML configuration files into JSON format.",
    category: "dev",
    icon: "Braces",
    keywords: ["yaml to json", "dev", "yaml to json"],
  },
  {
    slug: "json-to-yaml",
    name: "JSON to YAML",
    description: "Convert JSON to YAML.",
    longDescription: "Translate JSON objects into YAML format.",
    category: "dev",
    icon: "Braces",
    keywords: ["json to yaml", "dev", "json to yaml"],
  },
  {
    slug: "url-decode",
    name: "URL Decode",
    description: "Decode URL encoded strings.",
    longDescription: "Revert URL encoding back to readable text.",
    category: "dev",
    icon: "Link2",
    keywords: ["url decode", "dev", "url decode"],
  },
  {
    slug: "url-encode",
    name: "URL Encode",
    description: "Encode strings for URLs.",
    longDescription: "Safely encode special characters for URL parameters.",
    category: "dev",
    icon: "Link2",
    keywords: ["url encode", "dev", "url encode"],
  },
  {
    slug: "binary-to-text",
    name: "Binary to Text",
    description: "Convert binary to text.",
    longDescription: "Translate binary sequences into ASCII text.",
    category: "dev",
    icon: "Binary",
    keywords: ["binary to text", "dev", "binary to text"],
  },
  {
    slug: "text-to-binary",
    name: "Text to Binary",
    description: "Convert text to binary.",
    longDescription: "Translate ASCII text into binary sequences.",
    category: "dev",
    icon: "Binary",
    keywords: ["text to binary", "dev", "text to binary"],
  },
  {
    slug: "hex-to-text",
    name: "Hex to Text",
    description: "Convert hex to text.",
    longDescription: "Translate hexadecimal strings into text.",
    category: "dev",
    icon: "Binary",
    keywords: ["hex to text", "dev", "hex to text"],
  },
  {
    slug: "text-to-hex",
    name: "Text to Hex",
    description: "Convert text to hex.",
    longDescription: "Translate text into hexadecimal strings.",
    category: "dev",
    icon: "Binary",
    keywords: ["text to hex", "dev", "text to hex"],
  },
  {
    slug: "ascii-converter",
    name: "ASCII Converter",
    description: "Convert text to ASCII codes.",
    longDescription: "Get the ASCII numeric values for characters.",
    category: "dev",
    icon: "Terminal",
    keywords: ["ascii converter", "dev", "ascii converter"],
  },
  {
    slug: "hash-calculator",
    name: "Hash Calculator",
    description: "Calculate MD5, SHA1, SHA256.",
    longDescription: "Generate cryptographic hashes for text.",
    category: "dev",
    icon: "Lock",
    keywords: ["hash calculator", "dev", "hash calculator"],
  },
  {
    slug: "hmac-generator",
    name: "HMAC Generator",
    description: "Generate HMAC signatures.",
    longDescription: "Create Hash-based Message Authentication Codes.",
    category: "dev",
    icon: "Lock",
    keywords: ["hmac generator", "dev", "hmac generator"],
  },
  {
    slug: "rsa-generator",
    name: "RSA Key Generator",
    description: "Generate RSA key pairs.",
    longDescription: "Create public and private RSA keys locally.",
    category: "dev",
    icon: "Key",
    keywords: ["rsa key generator", "dev", "rsa generator"],
  },
  {
    slug: "css-gradient",
    name: "CSS Gradient Generator",
    description: "Create CSS gradients visually.",
    longDescription: "Generate linear and radial CSS gradient code.",
    category: "design",
    icon: "Palette",
    keywords: ["css gradient generator", "design", "css gradient"],
  },
  {
    slug: "box-shadow",
    name: "Box Shadow Generator",
    description: "Create CSS box shadows.",
    longDescription: "Visually design and export CSS box-shadow properties.",
    category: "design",
    icon: "Eye",
    keywords: ["box shadow generator", "design", "box shadow"],
  },
  {
    slug: "border-radius",
    name: "Border Radius Generator",
    description: "Create complex border radii.",
    longDescription: "Generate CSS for custom 8-point border radii.",
    category: "design",
    icon: "Palette",
    keywords: ["border radius generator", "design", "border radius"],
  },
  {
    slug: "glassmorphism",
    name: "Glassmorphism Generator",
    description: "Generate CSS glass effects.",
    longDescription: "Create frosted glass CSS styles instantly.",
    category: "design",
    icon: "Sparkles",
    keywords: ["glassmorphism generator", "design", "glassmorphism"],
  },
  {
    slug: "neumorphism",
    name: "Neumorphism Generator",
    description: "Generate neumorphic CSS.",
    longDescription: "Create soft UI CSS styles.",
    category: "design",
    icon: "Sparkles",
    keywords: ["neumorphism generator", "design", "neumorphism"],
  },
  {
    slug: "text-shadow",
    name: "Text Shadow Generator",
    description: "Create CSS text shadows.",
    longDescription: "Visually design and export CSS text-shadow properties.",
    category: "design",
    icon: "FileText",
    keywords: ["text shadow generator", "design", "text shadow"],
  },
  {
    slug: "meta-tags",
    name: "Meta Tag Generator",
    description: "Generate SEO meta tags.",
    longDescription: "Create HTML meta tags for SEO and social sharing.",
    category: "dev",
    icon: "Code",
    keywords: ["meta tag generator", "dev", "meta tags"],
  },
  {
    slug: "open-graph",
    name: "Open Graph Generator",
    description: "Generate OG tags.",
    longDescription: "Create Open Graph tags for Facebook and Twitter sharing.",
    category: "dev",
    icon: "Link2",
    keywords: ["open graph generator", "dev", "open graph"],
  },
  {
    slug: "twitter-card",
    name: "Twitter Card Generator",
    description: "Generate Twitter cards.",
    longDescription: "Create meta tags for rich Twitter link previews.",
    category: "dev",
    icon: "Link2",
    keywords: ["twitter card generator", "dev", "twitter card"],
  },
  {
    slug: "robots-txt",
    name: "Robots.txt Generator",
    description: "Generate robots.txt files.",
    longDescription: "Create rules for search engine crawlers.",
    category: "dev",
    icon: "Terminal",
    keywords: ["robots.txt generator", "dev", "robots txt"],
  },
  {
    slug: "sitemap-generator",
    name: "Sitemap Generator",
    description: "Generate XML sitemaps.",
    longDescription: "Create basic XML sitemaps for websites.",
    category: "dev",
    icon: "Link2",
    keywords: ["sitemap generator", "dev", "sitemap generator"],
  },
  {
    slug: "htaccess-generator",
    name: "Htaccess Generator",
    description: "Generate .htaccess rules.",
    longDescription: "Create common Apache server configuration rules.",
    category: "dev",
    icon: "Terminal",
    keywords: ["htaccess generator", "dev", "htaccess generator"],
  },
  {
    slug: "string-manipulation",
    name: "String Manipulation",
    description: "Manipulate strings in bulk.",
    longDescription: "Apply various transformations to text strings.",
    category: "text",
    icon: "CaseSensitive",
    keywords: ["string manipulation", "text", "string manipulation"],
  },
  {
    slug: "remove-line-breaks",
    name: "Remove Line Breaks",
    description: "Remove newlines from text.",
    longDescription: "Collapse multi-line text into a single paragraph.",
    category: "text",
    icon: "FileText",
    keywords: ["remove line breaks", "text", "remove line breaks"],
  },
  {
    slug: "remove-spaces",
    name: "Remove Extra Spaces",
    description: "Remove duplicate spaces.",
    longDescription: "Clean up text by removing extra whitespaces.",
    category: "text",
    icon: "FileText",
    keywords: ["remove extra spaces", "text", "remove spaces"],
  },
  {
    slug: "extract-emails",
    name: "Extract Emails",
    description: "Extract email addresses.",
    longDescription: "Find and extract all email addresses from a block of text.",
    category: "text",
    icon: "SearchCode",
    keywords: ["extract emails", "text", "extract emails"],
  },
  {
    slug: "extract-urls",
    name: "Extract URLs",
    description: "Extract links from text.",
    longDescription: "Find and extract all URLs from a block of text.",
    category: "text",
    icon: "Link2",
    keywords: ["extract urls", "text", "extract urls"],
  },
  {
    slug: "sort-lines",
    name: "Sort Lines",
    description: "Alphabetize text lines.",
    longDescription: "Sort lines of text alphabetically or numerically.",
    category: "text",
    icon: "FileText",
    keywords: ["sort lines", "text", "sort lines"],
  },
  {
    slug: "shuffle-lines",
    name: "Shuffle Lines",
    description: "Randomize text lines.",
    longDescription: "Shuffle the order of lines in a text block.",
    category: "text",
    icon: "FileText",
    keywords: ["shuffle lines", "text", "shuffle lines"],
  },
  {
    slug: "reverse-lines",
    name: "Reverse Lines",
    description: "Reverse line order.",
    longDescription: "Flip the order of lines in a text block.",
    category: "text",
    icon: "FileText",
    keywords: ["reverse lines", "text", "reverse lines"],
  },
  {
    slug: "remove-duplicates",
    name: "Duplicate Line Remover",
    description: "Remove duplicate lines.",
    longDescription: "Filter out repeated lines from text.",
    category: "text",
    icon: "FileText",
    keywords: ["duplicate line remover", "text", "remove duplicates"],
  },
  {
    slug: "add-prefix-suffix",
    name: "Prefix/Suffix Adder",
    description: "Add text to every line.",
    longDescription: "Append or prepend text to every line in a block.",
    category: "text",
    icon: "FileText",
    keywords: ["prefix/suffix adder", "text", "add prefix suffix"],
  },
  {
    slug: "find-replace",
    name: "Find and Replace",
    description: "Bulk find and replace.",
    longDescription: "Replace occurrences of text with support for regex.",
    category: "text",
    icon: "SearchCode",
    keywords: ["find and replace", "text", "find replace"],
  },
  {
    slug: "markdown-table",
    name: "Markdown Table Generator",
    description: "Generate MD tables.",
    longDescription: "Easily create and format markdown tables.",
    category: "dev",
    icon: "Braces",
    keywords: ["markdown table generator", "dev", "markdown table"],
  },
  {
    slug: "json-stringify",
    name: "JSON Stringify",
    description: "Stringify JSON objects.",
    longDescription: "Convert JSON objects into escaped strings.",
    category: "dev",
    icon: "Braces",
    keywords: ["json stringify", "dev", "json stringify"],
  },
  {
    slug: "json-parse",
    name: "JSON Parse",
    description: "Parse JSON strings.",
    longDescription: "Convert escaped JSON strings back into objects.",
    category: "dev",
    icon: "Braces",
    keywords: ["json parse", "dev", "json parse"],
  },
  {
    slug: "slug-generator",
    name: "URL Slug Generator",
    description: "Generate SEO friendly slugs.",
    longDescription: "Convert text into URL-friendly slugs.",
    category: "text",
    icon: "Link2",
    keywords: ["url slug generator", "text", "slug generator"],
  },
  {
    slug: "title-case",
    name: "Title Case Converter",
    description: "Convert to Title Case.",
    longDescription: "Capitalize text according to title casing rules.",
    category: "text",
    icon: "CaseSensitive",
    keywords: ["title case converter", "text", "title case"],
  },
  {
    slug: "camel-case",
    name: "Camel Case Converter",
    description: "Convert to camelCase.",
    longDescription: "Transform text into programming camelCase.",
    category: "text",
    icon: "CaseSensitive",
    keywords: ["camel case converter", "text", "camel case"],
  },
  {
    slug: "snake-case",
    name: "Snake Case Converter",
    description: "Convert to snake_case.",
    longDescription: "Transform text into programming snake_case.",
    category: "text",
    icon: "CaseSensitive",
    keywords: ["snake case converter", "text", "snake case"],
  },
  {
    slug: "kebab-case",
    name: "Kebab Case Converter",
    description: "Convert to kebab-case.",
    longDescription: "Transform text into programming kebab-case.",
    category: "text",
    icon: "CaseSensitive",
    keywords: ["kebab case converter", "text", "kebab case"],
  },
  {
    slug: "pascal-case",
    name: "Pascal Case Converter",
    description: "Convert to PascalCase.",
    longDescription: "Transform text into programming PascalCase.",
    category: "text",
    icon: "CaseSensitive",
    keywords: ["pascal case converter", "text", "pascal case"],
  },
  {
    slug: "constant-case",
    name: "Constant Case Converter",
    description: "Convert to CONSTANT_CASE.",
    longDescription: "Transform text into programming CONSTANT_CASE.",
    category: "text",
    icon: "CaseSensitive",
    keywords: ["constant case converter", "text", "constant case"],
  },
  {
    slug: "dot-case",
    name: "Dot Case Converter",
    description: "Convert to dot.case.",
    longDescription: "Transform text into programming dot.case.",
    category: "text",
    icon: "CaseSensitive",
    keywords: ["dot case converter", "text", "dot case"],
  },
  {
    slug: "path-case",
    name: "Path Case Converter",
    description: "Convert to path/case.",
    longDescription: "Transform text into programming path/case.",
    category: "text",
    icon: "CaseSensitive",
    keywords: ["path case converter", "text", "path case"],
  },
  {
    slug: "sentence-case",
    name: "Sentence Case Converter",
    description: "Convert to Sentence case.",
    longDescription: "Capitalize the first letter of each sentence.",
    category: "text",
    icon: "CaseSensitive",
    keywords: ["sentence case converter", "text", "sentence case"],
  },
  {
    slug: "toggle-case",
    name: "Toggle Case Converter",
    description: "tOGGLE cASE.",
    longDescription: "Invert the case of every character.",
    category: "text",
    icon: "CaseSensitive",
    keywords: ["toggle case converter", "text", "toggle case"],
  },
  {
    slug: "alternating-case",
    name: "Alternating Case",
    description: "aLtErNaTiNg cAsE.",
    longDescription: "Alternate between lower and upper case.",
    category: "text",
    icon: "CaseSensitive",
    keywords: ["alternating case", "text", "alternating case"],
  },
  {
    slug: "wide-text",
    name: "Wide Text Generator",
    description: "W I D E  T E X T.",
    longDescription: "Add spaces between characters for aesthetic text.",
    category: "text",
    icon: "FileText",
    keywords: ["wide text generator", "text", "wide text"],
  },
  {
    slug: "zalgo-text",
    name: "Zalgo Text Generator",
    description: "Generate glitched text.",
    longDescription: "Add Zalgo glitch effects to your text.",
    category: "text",
    icon: "FileText",
    keywords: ["zalgo text generator", "text", "zalgo text"],
  },
  {
    slug: "upside-down",
    name: "Upside Down Text",
    description: "Flip text upside down.",
    longDescription: "Rotate characters 180 degrees.",
    category: "text",
    icon: "FileText",
    keywords: ["upside down text", "text", "upside down"],
  },
  {
    slug: "morse-code",
    name: "Morse Code Converter",
    description: "Convert to/from Morse code.",
    longDescription: "Translate text to Morse code dots and dashes.",
    category: "text",
    icon: "Binary",
    keywords: ["morse code converter", "text", "morse code"],
  },
  {
    slug: "braille-translator",
    name: "Braille Translator",
    description: "Convert text to Braille.",
    longDescription: "Translate text into unicode Braille patterns.",
    category: "text",
    icon: "Eye",
    keywords: ["braille translator", "text", "braille translator"],
  },
  {
    slug: "rot13-decoder",
    name: "ROT13 Decoder",
    description: "Decode ROT13 ciphers.",
    longDescription: "Apply the ROT13 substitution cipher to text.",
    category: "dev",
    icon: "Lock",
    keywords: ["rot13 decoder", "dev", "rot13 decoder"],
  },
  {
    slug: "bip39-generator",
    name: "BIP39 Mnemonic Generator",
    description: "Generate crypto seed phrases.",
    longDescription: "Generate secure 12 or 24 word mnemonic phrases.",
    category: "dev",
    icon: "Key",
    keywords: ["bip39 mnemonic generator", "dev", "bip39 generator"],
  },
  {
    slug: "vigenere-cipher",
    name: "Vigenere Cipher",
    description: "Encrypt/decrypt Vigenere.",
    longDescription: "Apply the Vigenère polyalphabetic substitution cipher.",
    category: "dev",
    icon: "Lock",
    keywords: ["vigenere cipher", "dev", "vigenere cipher"],
  },
];
