  {
    slug: "meta-tag-generator",
    name: "Meta Tag Generator",
    description: "Use our free online Meta Tag Generator tool instantly.",
    longDescription: "The Meta Tag Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["meta tag generator", "seo", "meta tag generator"],
  },
  {
    slug: "schema-markup-generator",
    name: "Schema Markup Generator",
    description: "Use our free online Schema Markup Generator tool instantly.",
    longDescription: "The Schema Markup Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["schema markup generator", "seo", "schema markup generator"],
  },
  {
    slug: "robots-txt-generator",
    name: "Robots.txt Generator",
    description: "Use our free online Robots.txt Generator tool instantly.",
    longDescription: "The Robots.txt Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["robots.txt generator", "seo", "robots txt generator"],
  },
  {
    slug: "sitemap-validator",
    name: "Sitemap Validator",
    description: "Use our free online Sitemap Validator tool instantly.",
    longDescription: "The Sitemap Validator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["sitemap validator", "seo", "sitemap validator"],
  },
  {
    slug: "open-graph-generator",
    name: "Open Graph Generator",
    description: "Use our free online Open Graph Generator tool instantly.",
    longDescription: "The Open Graph Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["open graph generator", "seo", "open graph generator"],
  },
  {
    slug: "twitter-card-generator",
    name: "Twitter Card Generator",
    description: "Use our free online Twitter Card Generator tool instantly.",
    longDescription: "The Twitter Card Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["twitter card generator", "seo", "twitter card generator"],
  },
  {
    slug: "canonical-url-checker",
    name: "Canonical URL Checker",
    description: "Use our free online Canonical URL Checker tool instantly.",
    longDescription: "The Canonical URL Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["canonical url checker", "seo", "canonical url checker"],
  },
  {
    slug: "hreflang-generator",
    name: "Hreflang Generator",
    description: "Use our free online Hreflang Generator tool instantly.",
    longDescription: "The Hreflang Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["hreflang generator", "seo", "hreflang generator"],
  },
  {
    slug: "redirect-checker",
    name: "Redirect Checker",
    description: "Use our free online Redirect Checker tool instantly.",
    longDescription: "The Redirect Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["redirect checker", "seo", "redirect checker"],
  },
  {
    slug: "keyword-density-checker",
    name: "Keyword Density Checker",
    description: "Use our free online Keyword Density Checker tool instantly.",
    longDescription: "The Keyword Density Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["keyword density checker", "seo", "keyword density checker"],
  },
  {
    slug: "keyword-difficulty-checker",
    name: "Keyword Difficulty Checker",
    description: "Use our free online Keyword Difficulty Checker tool instantly.",
    longDescription: "The Keyword Difficulty Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["keyword difficulty checker", "seo", "keyword difficulty checker"],
  },
  {
    slug: "serp-preview-tool",
    name: "SERP Preview Tool",
    description: "Use our free online SERP Preview Tool tool instantly.",
    longDescription: "The SERP Preview Tool is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["serp preview tool", "seo", "serp preview tool"],
  },
  {
    slug: "meta-description-generator",
    name: "Meta Description Generator",
    description: "Use our free online Meta Description Generator tool instantly.",
    longDescription: "The Meta Description Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["meta description generator", "seo", "meta description generator"],
  },
  {
    slug: "slug-generator",
    name: "Slug Generator",
    description: "Use our free online Slug Generator tool instantly.",
    longDescription: "The Slug Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["slug generator", "seo", "slug generator"],
  },
  {
    slug: "html-sitemap-generator",
    name: "HTML Sitemap Generator",
    description: "Use our free online HTML Sitemap Generator tool instantly.",
    longDescription: "The HTML Sitemap Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["html sitemap generator", "seo", "html sitemap generator"],
  },
  {
    slug: "favicon-checker",
    name: "Favicon Checker",
    description: "Use our free online Favicon Checker tool instantly.",
    longDescription: "The Favicon Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["favicon checker", "seo", "favicon checker"],
  },
  {
    slug: "broken-link-checker",
    name: "Broken Link Checker",
    description: "Use our free online Broken Link Checker tool instantly.",
    longDescription: "The Broken Link Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["broken link checker", "seo", "broken link checker"],
  },
  {
    slug: "utm-builder",
    name: "UTM Builder",
    description: "Use our free online UTM Builder tool instantly.",
    longDescription: "The UTM Builder is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["utm builder", "seo", "utm builder"],
  },
  {
    slug: "url-shortener",
    name: "URL Shortener",
    description: "Use our free online URL Shortener tool instantly.",
    longDescription: "The URL Shortener is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["url shortener", "seo", "url shortener"],
  },
  {
    slug: "redirect-generator",
    name: "Redirect Generator",
    description: "Use our free online Redirect Generator tool instantly.",
    longDescription: "The Redirect Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["redirect generator", "seo", "redirect generator"],
  },
  {
    slug: "page-speed-analyzer",
    name: "Page Speed Analyzer",
    description: "Use our free online Page Speed Analyzer tool instantly.",
    longDescription: "The Page Speed Analyzer is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["page speed analyzer", "seo", "page speed analyzer"],
  },
  {
    slug: "mobile-friendly-checker",
    name: "Mobile Friendly Checker",
    description: "Use our free online Mobile Friendly Checker tool instantly.",
    longDescription: "The Mobile Friendly Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["mobile friendly checker", "seo", "mobile friendly checker"],
  },
  {
    slug: "domain-age-checker",
    name: "Domain Age Checker",
    description: "Use our free online Domain Age Checker tool instantly.",
    longDescription: "The Domain Age Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["domain age checker", "seo", "domain age checker"],
  },
  {
    slug: "whois-lookup",
    name: "WHOIS Lookup",
    description: "Use our free online WHOIS Lookup tool instantly.",
    longDescription: "The WHOIS Lookup is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["whois lookup", "seo", "whois lookup"],
  },
  {
    slug: "dns-lookup",
    name: "DNS Lookup",
    description: "Use our free online DNS Lookup tool instantly.",
    longDescription: "The DNS Lookup is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "seo",
    icon: "Search",
    keywords: ["dns lookup", "seo", "dns lookup"],
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Use our free online JWT Decoder tool instantly.",
    longDescription: "The JWT Decoder is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["jwt decoder", "dev", "jwt decoder"],
  },
  {
    slug: "jwt-encoder",
    name: "JWT Encoder",
    description: "Use our free online JWT Encoder tool instantly.",
    longDescription: "The JWT Encoder is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["jwt encoder", "dev", "jwt encoder"],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Use our free online UUID Generator tool instantly.",
    longDescription: "The UUID Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["uuid generator", "dev", "uuid generator"],
  },
  {
    slug: "uuid-validator",
    name: "UUID Validator",
    description: "Use our free online UUID Validator tool instantly.",
    longDescription: "The UUID Validator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["uuid validator", "dev", "uuid validator"],
  },
  {
    slug: "curl-generator",
    name: "Curl Generator",
    description: "Use our free online Curl Generator tool instantly.",
    longDescription: "The Curl Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["curl generator", "dev", "curl generator"],
  },
  {
    slug: "api-request-tester",
    name: "API Request Tester",
    description: "Use our free online API Request Tester tool instantly.",
    longDescription: "The API Request Tester is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["api request tester", "dev", "api request tester"],
  },
  {
    slug: "graphql-formatter",
    name: "GraphQL Formatter",
    description: "Use our free online GraphQL Formatter tool instantly.",
    longDescription: "The GraphQL Formatter is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["graphql formatter", "dev", "graphql formatter"],
  },
  {
    slug: "xml-validator",
    name: "XML Validator",
    description: "Use our free online XML Validator tool instantly.",
    longDescription: "The XML Validator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["xml validator", "dev", "xml validator"],
  },
  {
    slug: "yaml-validator",
    name: "YAML Validator",
    description: "Use our free online YAML Validator tool instantly.",
    longDescription: "The YAML Validator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["yaml validator", "dev", "yaml validator"],
  },
  {
    slug: "toml-formatter",
    name: "TOML Formatter",
    description: "Use our free online TOML Formatter tool instantly.",
    longDescription: "The TOML Formatter is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["toml formatter", "dev", "toml formatter"],
  },
  {
    slug: "csv-viewer",
    name: "CSV Viewer",
    description: "Use our free online CSV Viewer tool instantly.",
    longDescription: "The CSV Viewer is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["csv viewer", "dev", "csv viewer"],
  },
  {
    slug: "csv-to-json",
    name: "CSV to JSON",
    description: "Use our free online CSV to JSON tool instantly.",
    longDescription: "The CSV to JSON is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["csv to json", "dev", "csv to json"],
  },
  {
    slug: "json-to-csv",
    name: "JSON to CSV",
    description: "Use our free online JSON to CSV tool instantly.",
    longDescription: "The JSON to CSV is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["json to csv", "dev", "json to csv"],
  },
  {
    slug: "xml-to-json",
    name: "XML to JSON",
    description: "Use our free online XML to JSON tool instantly.",
    longDescription: "The XML to JSON is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["xml to json", "dev", "xml to json"],
  },
  {
    slug: "json-diff-checker",
    name: "JSON Diff Checker",
    description: "Use our free online JSON Diff Checker tool instantly.",
    longDescription: "The JSON Diff Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["json diff checker", "dev", "json diff checker"],
  },
  {
    slug: "unix-timestamp-converter",
    name: "Unix Timestamp Converter",
    description: "Use our free online Unix Timestamp Converter tool instantly.",
    longDescription: "The Unix Timestamp Converter is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["unix timestamp converter", "dev", "unix timestamp converter"],
  },
  {
    slug: "regex-generator",
    name: "Regex Generator",
    description: "Use our free online Regex Generator tool instantly.",
    longDescription: "The Regex Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["regex generator", "dev", "regex generator"],
  },
  {
    slug: "cron-generator",
    name: "Cron Generator",
    description: "Use our free online Cron Generator tool instantly.",
    longDescription: "The Cron Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["cron generator", "dev", "cron generator"],
  },
  {
    slug: "http-header-checker",
    name: "HTTP Header Checker",
    description: "Use our free online HTTP Header Checker tool instantly.",
    longDescription: "The HTTP Header Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["http header checker", "dev", "http header checker"],
  },
  {
    slug: "mime-type-finder",
    name: "MIME Type Finder",
    description: "Use our free online MIME Type Finder tool instantly.",
    longDescription: "The MIME Type Finder is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["mime type finder", "dev", "mime type finder"],
  },
  {
    slug: "ssl-certificate-checker",
    name: "SSL Certificate Checker",
    description: "Use our free online SSL Certificate Checker tool instantly.",
    longDescription: "The SSL Certificate Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["ssl certificate checker", "dev", "ssl certificate checker"],
  },
  {
    slug: "port-checker",
    name: "Port Checker",
    description: "Use our free online Port Checker tool instantly.",
    longDescription: "The Port Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["port checker", "dev", "port checker"],
  },
  {
    slug: "base32-encoder",
    name: "Base32 Encoder",
    description: "Use our free online Base32 Encoder tool instantly.",
    longDescription: "The Base32 Encoder is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["base32 encoder", "dev", "base32 encoder"],
  },
  {
    slug: "hex-converter",
    name: "Hex Converter",
    description: "Use our free online Hex Converter tool instantly.",
    longDescription: "The Hex Converter is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["hex converter", "dev", "hex converter"],
  },
  {
    slug: "binary-converter",
    name: "Binary Converter",
    description: "Use our free online Binary Converter tool instantly.",
    longDescription: "The Binary Converter is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "dev",
    icon: "Terminal",
    keywords: ["binary converter", "dev", "binary converter"],
  },
  {
    slug: "svg-wave-generator",
    name: "SVG Wave Generator",
    description: "Use our free online SVG Wave Generator tool instantly.",
    longDescription: "The SVG Wave Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["svg wave generator", "design", "svg wave generator"],
  },
  {
    slug: "svg-blob-generator",
    name: "SVG Blob Generator",
    description: "Use our free online SVG Blob Generator tool instantly.",
    longDescription: "The SVG Blob Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["svg blob generator", "design", "svg blob generator"],
  },
  {
    slug: "css-animation-generator",
    name: "CSS Animation Generator",
    description: "Use our free online CSS Animation Generator tool instantly.",
    longDescription: "The CSS Animation Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["css animation generator", "design", "css animation generator"],
  },
  {
    slug: "css-grid-generator",
    name: "CSS Grid Generator",
    description: "Use our free online CSS Grid Generator tool instantly.",
    longDescription: "The CSS Grid Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["css grid generator", "design", "css grid generator"],
  },
  {
    slug: "flexbox-generator",
    name: "Flexbox Generator",
    description: "Use our free online Flexbox Generator tool instantly.",
    longDescription: "The Flexbox Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["flexbox generator", "design", "flexbox generator"],
  },
  {
    slug: "glassmorphism-generator",
    name: "Glassmorphism Generator",
    description: "Use our free online Glassmorphism Generator tool instantly.",
    longDescription: "The Glassmorphism Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["glassmorphism generator", "design", "glassmorphism generator"],
  },
  {
    slug: "neumorphism-generator",
    name: "Neumorphism Generator",
    description: "Use our free online Neumorphism Generator tool instantly.",
    longDescription: "The Neumorphism Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["neumorphism generator", "design", "neumorphism generator"],
  },
  {
    slug: "css-button-generator",
    name: "CSS Button Generator",
    description: "Use our free online CSS Button Generator tool instantly.",
    longDescription: "The CSS Button Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["css button generator", "design", "css button generator"],
  },
  {
    slug: "css-shadow-generator",
    name: "CSS Shadow Generator",
    description: "Use our free online CSS Shadow Generator tool instantly.",
    longDescription: "The CSS Shadow Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["css shadow generator", "design", "css shadow generator"],
  },
  {
    slug: "gradient-mesh-generator",
    name: "Gradient Mesh Generator",
    description: "Use our free online Gradient Mesh Generator tool instantly.",
    longDescription: "The Gradient Mesh Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["gradient mesh generator", "design", "gradient mesh generator"],
  },
  {
    slug: "color-blindness-simulator",
    name: "Color Blindness Simulator",
    description: "Use our free online Color Blindness Simulator tool instantly.",
    longDescription: "The Color Blindness Simulator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["color blindness simulator", "design", "color blindness simulator"],
  },
  {
    slug: "palette-extractor",
    name: "Palette Extractor",
    description: "Use our free online Palette Extractor tool instantly.",
    longDescription: "The Palette Extractor is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["palette extractor", "design", "palette extractor"],
  },
  {
    slug: "font-pair-generator",
    name: "Font Pair Generator",
    description: "Use our free online Font Pair Generator tool instantly.",
    longDescription: "The Font Pair Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["font pair generator", "design", "font pair generator"],
  },
  {
    slug: "svg-optimizer",
    name: "SVG Optimizer",
    description: "Use our free online SVG Optimizer tool instantly.",
    longDescription: "The SVG Optimizer is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["svg optimizer", "design", "svg optimizer"],
  },
  {
    slug: "qr-sticker-generator",
    name: "QR Sticker Generator",
    description: "Use our free online QR Sticker Generator tool instantly.",
    longDescription: "The QR Sticker Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["qr sticker generator", "design", "qr sticker generator"],
  },
  {
    slug: "mockup-generator",
    name: "Mockup Generator",
    description: "Use our free online Mockup Generator tool instantly.",
    longDescription: "The Mockup Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["mockup generator", "design", "mockup generator"],
  },
  {
    slug: "browser-frame-generator",
    name: "Browser Frame Generator",
    description: "Use our free online Browser Frame Generator tool instantly.",
    longDescription: "The Browser Frame Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["browser frame generator", "design", "browser frame generator"],
  },
  {
    slug: "icon-converter",
    name: "Icon Converter",
    description: "Use our free online Icon Converter tool instantly.",
    longDescription: "The Icon Converter is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["icon converter", "design", "icon converter"],
  },
  {
    slug: "css-loader-generator",
    name: "CSS Loader Generator",
    description: "Use our free online CSS Loader Generator tool instantly.",
    longDescription: "The CSS Loader Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["css loader generator", "design", "css loader generator"],
  },
  {
    slug: "favicon-pack-generator",
    name: "Favicon Pack Generator",
    description: "Use our free online Favicon Pack Generator tool instantly.",
    longDescription: "The Favicon Pack Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "design",
    icon: "Palette",
    keywords: ["favicon pack generator", "design", "favicon pack generator"],
  },
  {
    slug: "linkedin-headline-generator",
    name: "LinkedIn Headline Generator",
    description: "Use our free online LinkedIn Headline Generator tool instantly.",
    longDescription: "The LinkedIn Headline Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["linkedin headline generator", "social", "linkedin headline generator"],
  },
  {
    slug: "linkedin-summary-generator",
    name: "LinkedIn Summary Generator",
    description: "Use our free online LinkedIn Summary Generator tool instantly.",
    longDescription: "The LinkedIn Summary Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["linkedin summary generator", "social", "linkedin summary generator"],
  },
  {
    slug: "youtube-chapter-generator",
    name: "YouTube Chapter Generator",
    description: "Use our free online YouTube Chapter Generator tool instantly.",
    longDescription: "The YouTube Chapter Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["youtube chapter generator", "social", "youtube chapter generator"],
  },
  {
    slug: "youtube-timestamp-generator",
    name: "YouTube Timestamp Generator",
    description: "Use our free online YouTube Timestamp Generator tool instantly.",
    longDescription: "The YouTube Timestamp Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["youtube timestamp generator", "social", "youtube timestamp generator"],
  },
  {
    slug: "reel-hook-generator",
    name: "Reel Hook Generator",
    description: "Use our free online Reel Hook Generator tool instantly.",
    longDescription: "The Reel Hook Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["reel hook generator", "social", "reel hook generator"],
  },
  {
    slug: "viral-caption-generator",
    name: "Viral Caption Generator",
    description: "Use our free online Viral Caption Generator tool instantly.",
    longDescription: "The Viral Caption Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["viral caption generator", "social", "viral caption generator"],
  },
  {
    slug: "hashtag-analyzer",
    name: "Hashtag Analyzer",
    description: "Use our free online Hashtag Analyzer tool instantly.",
    longDescription: "The Hashtag Analyzer is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["hashtag analyzer", "social", "hashtag analyzer"],
  },
  {
    slug: "bio-link-generator",
    name: "Bio Link Generator",
    description: "Use our free online Bio Link Generator tool instantly.",
    longDescription: "The Bio Link Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["bio link generator", "social", "bio link generator"],
  },
  {
    slug: "emoji-combiner",
    name: "Emoji Combiner",
    description: "Use our free online Emoji Combiner tool instantly.",
    longDescription: "The Emoji Combiner is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["emoji combiner", "social", "emoji combiner"],
  },
  {
    slug: "thumbnail-title-analyzer",
    name: "Thumbnail Title Analyzer",
    description: "Use our free online Thumbnail Title Analyzer tool instantly.",
    longDescription: "The Thumbnail Title Analyzer is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["thumbnail title analyzer", "social", "thumbnail title analyzer"],
  },
  {
    slug: "username-availability-checker",
    name: "Username Availability Checker",
    description: "Use our free online Username Availability Checker tool instantly.",
    longDescription: "The Username Availability Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["username availability checker", "social", "username availability checker"],
  },
  {
    slug: "social-post-formatter",
    name: "Social Post Formatter",
    description: "Use our free online Social Post Formatter tool instantly.",
    longDescription: "The Social Post Formatter is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["social post formatter", "social", "social post formatter"],
  },
  {
    slug: "cta-generator",
    name: "CTA Generator",
    description: "Use our free online CTA Generator tool instantly.",
    longDescription: "The CTA Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["cta generator", "social", "cta generator"],
  },
  {
    slug: "comment-generator",
    name: "Comment Generator",
    description: "Use our free online Comment Generator tool instantly.",
    longDescription: "The Comment Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["comment generator", "social", "comment generator"],
  },
  {
    slug: "poll-generator",
    name: "Poll Generator",
    description: "Use our free online Poll Generator tool instantly.",
    longDescription: "The Poll Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["poll generator", "social", "poll generator"],
  },
  {
    slug: "giveaway-picker",
    name: "Giveaway Picker",
    description: "Use our free online Giveaway Picker tool instantly.",
    longDescription: "The Giveaway Picker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["giveaway picker", "social", "giveaway picker"],
  },
  {
    slug: "youtube-comment-picker",
    name: "YouTube Comment Picker",
    description: "Use our free online YouTube Comment Picker tool instantly.",
    longDescription: "The YouTube Comment Picker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["youtube comment picker", "social", "youtube comment picker"],
  },
  {
    slug: "viral-hook-generator",
    name: "Viral Hook Generator",
    description: "Use our free online Viral Hook Generator tool instantly.",
    longDescription: "The Viral Hook Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["viral hook generator", "social", "viral hook generator"],
  },
  {
    slug: "engagement-calculator",
    name: "Engagement Calculator",
    description: "Use our free online Engagement Calculator tool instantly.",
    longDescription: "The Engagement Calculator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["engagement calculator", "social", "engagement calculator"],
  },
  {
    slug: "trending-hashtag-finder",
    name: "Trending Hashtag Finder",
    description: "Use our free online Trending Hashtag Finder tool instantly.",
    longDescription: "The Trending Hashtag Finder is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "social",
    icon: "MessageCircle",
    keywords: ["trending hashtag finder", "social", "trending hashtag finder"],
  },
  {
    slug: "invoice-number-generator",
    name: "Invoice Number Generator",
    description: "Use our free online Invoice Number Generator tool instantly.",
    longDescription: "The Invoice Number Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["invoice number generator", "business", "invoice number generator"],
  },
  {
    slug: "gst-hsn-finder",
    name: "GST HSN Finder",
    description: "Use our free online GST HSN Finder tool instantly.",
    longDescription: "The GST HSN Finder is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["gst hsn finder", "business", "gst hsn finder"],
  },
  {
    slug: "profit-margin-analyzer",
    name: "Profit Margin Analyzer",
    description: "Use our free online Profit Margin Analyzer tool instantly.",
    longDescription: "The Profit Margin Analyzer is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["profit margin analyzer", "business", "profit margin analyzer"],
  },
  {
    slug: "break-even-calculator",
    name: "Break-even Calculator",
    description: "Use our free online Break-even Calculator tool instantly.",
    longDescription: "The Break-even Calculator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["break-even calculator", "business", "break even calculator"],
  },
  {
    slug: "sales-commission-calculator",
    name: "Sales Commission Calculator",
    description: "Use our free online Sales Commission Calculator tool instantly.",
    longDescription: "The Sales Commission Calculator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["sales commission calculator", "business", "sales commission calculator"],
  },
  {
    slug: "startup-burn-rate-calculator",
    name: "Startup Burn Rate Calculator",
    description: "Use our free online Startup Burn Rate Calculator tool instantly.",
    longDescription: "The Startup Burn Rate Calculator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["startup burn rate calculator", "business", "startup burn rate calculator"],
  },
  {
    slug: "roi-calculator",
    name: "ROI Calculator",
    description: "Use our free online ROI Calculator tool instantly.",
    longDescription: "The ROI Calculator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["roi calculator", "business", "roi calculator"],
  },
  {
    slug: "cac-calculator",
    name: "CAC Calculator",
    description: "Use our free online CAC Calculator tool instantly.",
    longDescription: "The CAC Calculator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["cac calculator", "business", "cac calculator"],
  },
  {
    slug: "ltv-calculator",
    name: "LTV Calculator",
    description: "Use our free online LTV Calculator tool instantly.",
    longDescription: "The LTV Calculator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["ltv calculator", "business", "ltv calculator"],
  },
  {
    slug: "salary-hike-calculator",
    name: "Salary Hike Calculator",
    description: "Use our free online Salary Hike Calculator tool instantly.",
    longDescription: "The Salary Hike Calculator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["salary hike calculator", "business", "salary hike calculator"],
  },
  {
    slug: "freelance-rate-calculator",
    name: "Freelance Rate Calculator",
    description: "Use our free online Freelance Rate Calculator tool instantly.",
    longDescription: "The Freelance Rate Calculator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["freelance rate calculator", "business", "freelance rate calculator"],
  },
  {
    slug: "pricing-calculator",
    name: "Pricing Calculator",
    description: "Use our free online Pricing Calculator tool instantly.",
    longDescription: "The Pricing Calculator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["pricing calculator", "business", "pricing calculator"],
  },
  {
    slug: "subscription-calculator",
    name: "Subscription Calculator",
    description: "Use our free online Subscription Calculator tool instantly.",
    longDescription: "The Subscription Calculator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["subscription calculator", "business", "subscription calculator"],
  },
  {
    slug: "business-name-score-checker",
    name: "Business Name Score Checker",
    description: "Use our free online Business Name Score Checker tool instantly.",
    longDescription: "The Business Name Score Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["business name score checker", "business", "business name score checker"],
  },
  {
    slug: "invoice-due-date-calculator",
    name: "Invoice Due Date Calculator",
    description: "Use our free online Invoice Due Date Calculator tool instantly.",
    longDescription: "The Invoice Due Date Calculator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["invoice due date calculator", "business", "invoice due date calculator"],
  },
  {
    slug: "quotation-builder",
    name: "Quotation Builder",
    description: "Use our free online Quotation Builder tool instantly.",
    longDescription: "The Quotation Builder is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["quotation builder", "business", "quotation builder"],
  },
  {
    slug: "receipt-builder",
    name: "Receipt Builder",
    description: "Use our free online Receipt Builder tool instantly.",
    longDescription: "The Receipt Builder is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["receipt builder", "business", "receipt builder"],
  },
  {
    slug: "tax-estimator",
    name: "Tax Estimator",
    description: "Use our free online Tax Estimator tool instantly.",
    longDescription: "The Tax Estimator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["tax estimator", "business", "tax estimator"],
  },
  {
    slug: "profit-split-calculator",
    name: "Profit Split Calculator",
    description: "Use our free online Profit Split Calculator tool instantly.",
    longDescription: "The Profit Split Calculator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["profit split calculator", "business", "profit split calculator"],
  },
  {
    slug: "expense-tracker",
    name: "Expense Tracker",
    description: "Use our free online Expense Tracker tool instantly.",
    longDescription: "The Expense Tracker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "business",
    icon: "Briefcase",
    keywords: ["expense tracker", "business", "expense tracker"],
  },
  {
    slug: "study-planner",
    name: "Study Planner",
    description: "Use our free online Study Planner tool instantly.",
    longDescription: "The Study Planner is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["study planner", "student", "study planner"],
  },
  {
    slug: "revision-planner",
    name: "Revision Planner",
    description: "Use our free online Revision Planner tool instantly.",
    longDescription: "The Revision Planner is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["revision planner", "student", "revision planner"],
  },
  {
    slug: "flashcard-generator",
    name: "Flashcard Generator",
    description: "Use our free online Flashcard Generator tool instantly.",
    longDescription: "The Flashcard Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["flashcard generator", "student", "flashcard generator"],
  },
  {
    slug: "assignment-planner",
    name: "Assignment Planner",
    description: "Use our free online Assignment Planner tool instantly.",
    longDescription: "The Assignment Planner is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["assignment planner", "student", "assignment planner"],
  },
  {
    slug: "citation-formatter",
    name: "Citation Formatter",
    description: "Use our free online Citation Formatter tool instantly.",
    longDescription: "The Citation Formatter is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["citation formatter", "student", "citation formatter"],
  },
  {
    slug: "apa-generator",
    name: "APA Generator",
    description: "Use our free online APA Generator tool instantly.",
    longDescription: "The APA Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["apa generator", "student", "apa generator"],
  },
  {
    slug: "mla-generator",
    name: "MLA Generator",
    description: "Use our free online MLA Generator tool instantly.",
    longDescription: "The MLA Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["mla generator", "student", "mla generator"],
  },
  {
    slug: "research-outline-generator",
    name: "Research Outline Generator",
    description: "Use our free online Research Outline Generator tool instantly.",
    longDescription: "The Research Outline Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["research outline generator", "student", "research outline generator"],
  },
  {
    slug: "quiz-generator",
    name: "Quiz Generator",
    description: "Use our free online Quiz Generator tool instantly.",
    longDescription: "The Quiz Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["quiz generator", "student", "quiz generator"],
  },
  {
    slug: "random-question-picker",
    name: "Random Question Picker",
    description: "Use our free online Random Question Picker tool instantly.",
    longDescription: "The Random Question Picker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["random question picker", "student", "random question picker"],
  },
  {
    slug: "study-timer",
    name: "Study Timer",
    description: "Use our free online Study Timer tool instantly.",
    longDescription: "The Study Timer is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["study timer", "student", "study timer"],
  },
  {
    slug: "reading-time-calculator",
    name: "Reading Time Calculator",
    description: "Use our free online Reading Time Calculator tool instantly.",
    longDescription: "The Reading Time Calculator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["reading time calculator", "student", "reading time calculator"],
  },
  {
    slug: "exam-countdown",
    name: "Exam Countdown",
    description: "Use our free online Exam Countdown tool instantly.",
    longDescription: "The Exam Countdown is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["exam countdown", "student", "exam countdown"],
  },
  {
    slug: "gpa-planner",
    name: "GPA Planner",
    description: "Use our free online GPA Planner tool instantly.",
    longDescription: "The GPA Planner is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["gpa planner", "student", "gpa planner"],
  },
  {
    slug: "attendance-goal-calculator",
    name: "Attendance Goal Calculator",
    description: "Use our free online Attendance Goal Calculator tool instantly.",
    longDescription: "The Attendance Goal Calculator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["attendance goal calculator", "student", "attendance goal calculator"],
  },
  {
    slug: "notes-formatter",
    name: "Notes Formatter",
    description: "Use our free online Notes Formatter tool instantly.",
    longDescription: "The Notes Formatter is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["notes formatter", "student", "notes formatter"],
  },
  {
    slug: "formula-sheet-generator",
    name: "Formula Sheet Generator",
    description: "Use our free online Formula Sheet Generator tool instantly.",
    longDescription: "The Formula Sheet Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["formula sheet generator", "student", "formula sheet generator"],
  },
  {
    slug: "homework-tracker",
    name: "Homework Tracker",
    description: "Use our free online Homework Tracker tool instantly.",
    longDescription: "The Homework Tracker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["homework tracker", "student", "homework tracker"],
  },
  {
    slug: "subject-timetable-generator",
    name: "Subject Timetable Generator",
    description: "Use our free online Subject Timetable Generator tool instantly.",
    longDescription: "The Subject Timetable Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["subject timetable generator", "student", "subject timetable generator"],
  },
  {
    slug: "essay-outline-generator",
    name: "Essay Outline Generator",
    description: "Use our free online Essay Outline Generator tool instantly.",
    longDescription: "The Essay Outline Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "student",
    icon: "BookOpen",
    keywords: ["essay outline generator", "student", "essay outline generator"],
  },
  {
    slug: "internet-speed-test",
    name: "Internet Speed Test",
    description: "Use our free online Internet Speed Test tool instantly.",
    longDescription: "The Internet Speed Test is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["internet speed test", "utility", "internet speed test"],
  },
  {
    slug: "webcam-test",
    name: "Webcam Test",
    description: "Use our free online Webcam Test tool instantly.",
    longDescription: "The Webcam Test is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["webcam test", "utility", "webcam test"],
  },
  {
    slug: "microphone-test",
    name: "Microphone Test",
    description: "Use our free online Microphone Test tool instantly.",
    longDescription: "The Microphone Test is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["microphone test", "utility", "microphone test"],
  },
  {
    slug: "keyboard-tester",
    name: "Keyboard Tester",
    description: "Use our free online Keyboard Tester tool instantly.",
    longDescription: "The Keyboard Tester is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["keyboard tester", "utility", "keyboard tester"],
  },
  {
    slug: "mouse-tester",
    name: "Mouse Tester",
    description: "Use our free online Mouse Tester tool instantly.",
    longDescription: "The Mouse Tester is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["mouse tester", "utility", "mouse tester"],
  },
  {
    slug: "screen-resolution-checker",
    name: "Screen Resolution Checker",
    description: "Use our free online Screen Resolution Checker tool instantly.",
    longDescription: "The Screen Resolution Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["screen resolution checker", "utility", "screen resolution checker"],
  },
  {
    slug: "browser-information",
    name: "Browser Information",
    description: "Use our free online Browser Information tool instantly.",
    longDescription: "The Browser Information is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["browser information", "utility", "browser information"],
  },
  {
    slug: "device-information",
    name: "Device Information",
    description: "Use our free online Device Information tool instantly.",
    longDescription: "The Device Information is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["device information", "utility", "device information"],
  },
  {
    slug: "battery-status-checker",
    name: "Battery Status Checker",
    description: "Use our free online Battery Status Checker tool instantly.",
    longDescription: "The Battery Status Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["battery status checker", "utility", "battery status checker"],
  },
  {
    slug: "ip-geolocation",
    name: "IP Geolocation",
    description: "Use our free online IP Geolocation tool instantly.",
    longDescription: "The IP Geolocation is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["ip geolocation", "utility", "ip geolocation"],
  },
  {
    slug: "time-zone-finder",
    name: "Time Zone Finder",
    description: "Use our free online Time Zone Finder tool instantly.",
    longDescription: "The Time Zone Finder is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["time zone finder", "utility", "time zone finder"],
  },
  {
    slug: "network-ping-test",
    name: "Network Ping Test",
    description: "Use our free online Network Ping Test tool instantly.",
    longDescription: "The Network Ping Test is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["network ping test", "utility", "network ping test"],
  },
  {
    slug: "internet-latency-checker",
    name: "Internet Latency Checker",
    description: "Use our free online Internet Latency Checker tool instantly.",
    longDescription: "The Internet Latency Checker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["internet latency checker", "utility", "internet latency checker"],
  },
  {
    slug: "clipboard-cleaner",
    name: "Clipboard Cleaner",
    description: "Use our free online Clipboard Cleaner tool instantly.",
    longDescription: "The Clipboard Cleaner is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["clipboard cleaner", "utility", "clipboard cleaner"],
  },
  {
    slug: "random-picker",
    name: "Random Picker",
    description: "Use our free online Random Picker tool instantly.",
    longDescription: "The Random Picker is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["random picker", "utility", "random picker"],
  },
  {
    slug: "spin-wheel",
    name: "Spin Wheel",
    description: "Use our free online Spin Wheel tool instantly.",
    longDescription: "The Spin Wheel is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["spin wheel", "utility", "spin wheel"],
  },
  {
    slug: "coin-flip",
    name: "Coin Flip",
    description: "Use our free online Coin Flip tool instantly.",
    longDescription: "The Coin Flip is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["coin flip", "utility", "coin flip"],
  },
  {
    slug: "dice-roller",
    name: "Dice Roller",
    description: "Use our free online Dice Roller tool instantly.",
    longDescription: "The Dice Roller is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["dice roller", "utility", "dice roller"],
  },
  {
    slug: "password-audit",
    name: "Password Audit",
    description: "Use our free online Password Audit tool instantly.",
    longDescription: "The Password Audit is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["password audit", "utility", "password audit"],
  },
  {
    slug: "random-secret-generator",
    name: "Random Secret Generator",
    description: "Use our free online Random Secret Generator tool instantly.",
    longDescription: "The Random Secret Generator is a powerful online tool designed to help you with your tasks quickly and securely directly from your browser.",
    category: "utility",
    icon: "Wrench",
    keywords: ["random secret generator", "utility", "random secret generator"],
  },